# примеры API-запросов

@baseUrl = http://127.0.0.1:8000
@authUrl = http://127.0.0.1:8000/auth
@email = e.ryzhkov@okko.tv
@password = L00pback
@access = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwNTcyODY3LCJpYXQiOjE3NzA1NzI1NjcsImp0aSI6ImMxOTAwZTExZWJlZjRlN2M5YmY3NzQ3M2NmYTcxNzRjIiwidXNlcl9pZCI6IjEifQ.2Ooh4C3SeJ-3gKNIV_bLDJawBvkNAvI5IXZ4S0zVtf8

###

# JWT: получить токены
POST {{authUrl}}/token/
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

# JWT: обновить access token
POST {{authUrl}}/token/refresh/
Content-Type: application/json

{
    "refresh": "YOUR_REFRESH_TOKEN"
}

###

# JWT: профиль текущего пользователя
GET {{authUrl}}/me/
Authorization: Bearer {{access}}
Content-Type: application/json

###

# JWT: регистрация пользователя (только админ)
POST {{authUrl}}/register/
Authorization: Bearer {{access}}
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "StrongPass123"
}



### GENERAL

#  получение списка сайтов
GET {{baseUrl}}/site_location
Content-Type: application/json



### ASSETS
 
#  получение списка assets
GET {{baseUrl}}/assets
Content-Type: application/json
   
###

# Создание assets
POST  {{baseUrl}}/assets/create
Content-Type: application/json

{
    "items": [
        {
            "inventoryitem_type_id": 1,
            "count": 2,
            "serials": ["SN0012", "SN0021"]
        },
        {
            "inventoryitem_type_id": 2,
            "count": 3,
            "serials": [] 
        }
    ],
    "storage_location_id": 38,
    "delivery_task": "input"
}   
###

# Ремонта девайса из ЗИП
POST {{baseUrl}}/assets/repair
Content-Type: application/json

{
    "device_id": 1111,
    "asset_ids": [3,4],
    "jira_task": "DC-1647"
}

###

# Модернизация устройства
POST {{baseUrl}}/assets/modernization
Content-Type: application/json

{
    "device_id": 1111,
    "asset_ids": [6,7,8],
    "jira_task": "DC-7461"
}





###  DEVICES

# получение списка устройств
GET {{baseUrl}}/device_types
Content-Type: application/json

###

# создание устройства
POST {{baseUrl}}/devices/create
Content-Type: application/json

[
    {
        "name": "test75",
        "asset_tag": "OKKOS75",
        "serial": "test75",
        "location": 3,
        "role": 2, 
        "manufacturer": "Supermicro", 
        "device_type": 4, 
        "status": "inventory", 
        "site": 9,
        "custom_fields": {
            "DeliveryTask": "TASK-2024-003",
            "CommissioningDate": "2024-01-20"
        }
    }
]

###

# Удаление устройства
DELETE  {{baseUrl}}/devices/delete
Content-Type: application/json

{
    "asset_tag": "OKKOS2120"
}


### CABLES

# Создание кабелей
POST {{baseUrl}}/cables/create
Content-Type: application/json

[
    {"dev_a": "network_test", "port_a": "et-0/0/14", "dev_b": "test73", "port_b": "Gig-E 1", "int_type": "1000base-t"},
    {"dev_a": "network_test", "port_a": "et-0/0/16", "dev_b": "test73", "port_b": "Gig-E 2", "int_type": "1000base-t"}
]
sabled with A
###

